### ISSUE TITLE
test pure wont pass any more

### ISSUE THREAD

**Issue by anyayunli** [teropa/redux-voting-client#19]
```
it('renders as a pure component', () => {
  const pair = ['Trainspotting', '28 Days Later'];
  const component = renderIntoDocument(
    <Voting pair={pair} />
  );

  let firstButton = scryRenderedDOMComponentsWithTag(component,   'button')[0];
  expect(firstButton.textContent).to.equal('Trainspotting');

  pair[0] = 'Sunshine';
  const component2 = renderIntoDocument(
    <Voting pair={pair} />
  );
  firstButton = scryRenderedDOMComponentsWithTag(component2, 'button')[0];
  expect(firstButton.textContent).to.equal('Trainspotting');
});
```
at least in my test, `expect(firstButton.textContent).to.equal('Sunshine');`
I guess here we should use a immuatable list

**Comment by Jedeu** [comment]
@anyayunli you are correct. If you follow along with the remaining sections until **Writing The UI for The Results Screen And Handling Routing**, you will see how he goes about using an immutable list and making the tests pass.

**Comment by anyayunli** [comment]
close, looks like this repo is not actively maintained now
